name: Python CI

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*-python"
    paths:
      - "python-version/**"
      - ".github/workflows/python-ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "python-version/**"
      - ".github/workflows/python-ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          elif [ -f pyproject.toml ]; then
            python -m pip install --upgrade pip
            pip install -e .
          else
            echo "Nenhuma dependência para instalar."
          fi

      - name: Run tests
        run: |
          if [ -d tests ]; then
            python -m pip install --upgrade pip
            python -m pip install pytest
            pytest
          else
            echo "Nenhum teste automatizado encontrado."
          fi
